from typing import Literal

from pydantic import BaseModel, Field, field_validator


class EvidenceAnalysis(BaseModel):
    evidence_summary: str = Field(..., description="Concise summary of submitted evidence.")
    observations: list[str] = Field(default_factory=list, description="Visible or reported observations.")
    flags: list[str] = Field(default_factory=list, description="Potential inconsistencies or concerns.")
    missing_information: list[str] = Field(default_factory=list, description="Information that would strengthen the assessment.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0 and 1.")
    demo: bool = Field(default=False, description="True when this output was generated by the fallback/demo path instead of a live LLM.")


class WaterQualityAnalysis(BaseModel):
    quality_assessment: str = Field(..., description="Assessment of possible water quality concerns.")
    possible_contaminants: list[str] = Field(default_factory=list, description="Possible contaminant categories.")
    risk_factors: list[str] = Field(default_factory=list, description="Factors that may increase concern.")
    recommended_tests: list[str] = Field(default_factory=list, description="Recommended laboratory or field tests.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0 and 1.")
    demo: bool = Field(default=False, description="True when this output was generated by the fallback/demo path instead of a live LLM.")


class VerificationAnalysis(BaseModel):
    verification_score: float = Field(..., ge=0.0, le=1.0, description="Verification score between 0 and 1.")
    verification_status: Literal["LOW", "MEDIUM", "HIGH"] = Field(..., description="Overall verification status.")
    anomaly_flags: list[str] = Field(default_factory=list, description="Detected contradictions or anomalies.")
    missing_evidence: list[str] = Field(default_factory=list, description="Evidence that is missing or weak.")
    reasoning_summary: str = Field(..., description="Brief reasoning for the verification assessment.")
    demo: bool = Field(default=False, description="True when this output was generated by the fallback/demo path instead of a live LLM.")


class RiskAssessment(BaseModel):
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Risk score between 0 and 100.")
    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(..., description="Risk level.")
    priority: Literal["LOW", "MEDIUM", "HIGH", "URGENT"] = Field(..., description="Recommended priority.")
    risk_factors: list[str] = Field(default_factory=list, description="Factors contributing to risk.")
    recommended_urgency: str = Field(..., description="Recommended urgency of response.")
    affected_area_estimate: str = Field(..., description="Estimated affected area described qualitatively.")
    demo: bool = Field(default=False, description="True when this output was generated by the fallback/demo path instead of a live LLM.")


class ResolutionPlan(BaseModel):
    action_plan: list[str] = Field(default_factory=list, description="Recommended actions.")
    urgency: str = Field(..., description="Urgency of the recommended response.")
    recommended_timeline: str = Field(..., description="Suggested timeline for action.")
    stakeholders: list[str] = Field(default_factory=list, description="Stakeholders to involve.")
    escalation_reason: str = Field(default="", description="Reason for escalation, if any.")
    summary: str = Field(..., description="Summary of the resolution plan.")
    demo: bool = Field(default=False, description="True when this output was generated by the fallback/demo path instead of a live LLM.")


class FinalAnalysis(BaseModel):
    overall_risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(..., description="Overall risk level.")
    overall_confidence: float = Field(..., ge=0.0, le=1.0, description="Average confidence across agents.")
    summary: str = Field(..., description="High-level summary of the AI analysis.")
    recommended_next_steps: list[str] = Field(default_factory=list, description="Top recommended next steps.")
    demo: bool = Field(default=False, description="True when any part of this analysis used the fallback/demo path.")


class AgentConfig(BaseModel):
    name: str
    description: str
    system_prompt: str
